name: Reusable - Qlty Coverage Upload

on:
  workflow_call:
    secrets:
      QLTY_COVERAGE_TOKEN:
        required: true

jobs:
  upload-coverage:
    name: Upload Coverage to Qlty
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: Harden the runner (Audit outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Download coverage artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: coverage-report
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage to Qlty
        uses: qltysh/qlty-action/coverage@a19242102d17e497f437d7466aa01b528537e899  # v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage.xml
