name: Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 1'
  push:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecard:
    uses: ByronWilliamsCPA/.github/.github/workflows/python-scorecard.yml@e067cdb7294f6221dbde74ef1f4c3ca735eed570 # main
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    secrets:
      SCORECARD_TOKEN: ${{ secrets.SCORECARD_TOKEN }}
