name: Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 1'
  push:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecard:
    uses: ByronWilliamsCPA/.github/.github/workflows/python-scorecard.yml@4e0fd54428d6745b04e2316f85d585109d7db02b # main
    permissions:
      security-events: write
      contents: read
      actions: read
    secrets:
      SCORECARD_TOKEN: ${{ secrets.SCORECARD_TOKEN }}
