name: Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 1'
  push:
    branches: ["main"]

permissions: read-all

concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecard:
    uses: ./.github/workflows/reusable-scorecard.yml
    secrets:
      SCORECARD_TOKEN: ${{ secrets.SCORECARD_TOKEN }}
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
